#!/usr/bin/env bash

sudo pacman -Syu --noconfirm ripgrep 
sudo pacman -Syu --noconfirm fzf
sudo pacman -Syu --noconfirm lazygit 
sudo pacman -Syu --noconfirm eza 
sudo pacman -Syu --noconfirm zoxide 
sudo pacman -Syu --noconfirm yazi
sudo pacman -Syu --noconfirm ttf-cascadia-code-nerd 
sudo pacman -Syu --noconfirm fuzzel
sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si

sudo pacman -Syu --noconfirm docker
sudo systemctl enable docker.service
sudo systemctl start docker.service
sudo usermod -aG docker "$USER"
DOCKER_CONFIG='/etc/docker/daemon.json'
sudo mkdir -p /etc/docker
echo '{
    "log-driver": "json-file",
    "log-opts": {
        "max-size": "10m",
        "max-file": "5"
    }
}' | sudo tee "$DOCKER_CONFIG" > /dev/null
sudo systemctl restart docker.service
sudo pacman -Syu --noconfirm mysql-clients postgresql-libs
sudo docker run -d --restart unless-stopped -p "127.0.0.1:3306:3306" --name=mysql8 \
    -e MYSQL_ROOT_PASSWORD= \
    -e MYSQL_ALLOW_EMPTY_PASSWORD=true \
    mysql:8.4
sudo docker run -d --restart unless-stopped -p "127.0.0.1:5432:5432" --name=postgres16 \
    -e POSTGRES_HOST_AUTH_METHOD=trust \
    postgres:16

sudo pacman -Syu --noconfirm swaync
sudo pacman -Syu --noconfirm libnotify
sudo pacman -Syu --noconfirm hypridle
sudo pacman -Syu --noconfirm hyprpaper
sudo pacman -Syu --noconfirm waybar 
sudo pacman -Syu --noconfirm hyprlock 
rm -rf ~/.config/waybar
ln -s $HOME/dotfiles/backgrounds $HOME/.config/backgrounds
rm -rf ~/.config/hypr
ln -s $HOME/dotfiles/hypr/ $HOME/.config/hypr
ln -s $HOME/dotfiles/waybar $HOME/.config/waybar

sudo pacman -Syu --noconfirm kitty
rm -rf ~/.config/kitty
ln -s $HOME/dotfiles/kitty/ $HOME/.config/kitty


sudo pacman -Syu --noconfirm lua 
sudo pacman -Syu --noconfirm luarocks 
sudo pacman -Syu --noconfirm python 
sudo pacman -Syu --noconfirm python-pip
sudo pacman -Syu --noconfirm go
sudo pacman -Syu --noconfirm rust

sudo pacman -Syu --noconfirm npm 
sudo pacman -Syu --noconfirm nodejs 
sudo npm install -g typescript-language-server typescript

sudo pacman -Syu --noconfirm neovim 
rm -rf ~/.config/nvim
ln -s $HOME/dev/dotfiles/nvim/ $HOME/.config/nvim

sudo pacman -Syu --noconfirm tmux

mkdir -p "$HOME/.local/bin/"
ln -s "$HOME/dotfiles/scripts/tmux-sessionizer" "$HOME/.local/bin/tmux-sessionizer"

yay -S lazydocker
yay -S hyprshot

sudo pacman -Syu --noconfirm zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

