#!/usr/bin/env bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

grep=""
dry_run="0"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry)
            dry_run="1"
            ;;
        --*)
            grep="${1:2}"  
            ;;
        *)
            echo "Invalid argument: $1"
            exit 1
            ;;
    esac
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "RUN: env: $env -- grep: $grep"

runs_dir=$(find "$script_dir/runs" -mindepth 1 -maxdepth 1 -executable | sort)

if [[ -n "$grep" ]]; then
    for s in $runs_dir; do
        if [[ "$s" == *"$grep"* ]]; then
            log "running script: $s"
            if [[ $dry_run == "0" ]]; then
                "$s"
            fi
        else
            log "grep \"$grep\" filtered out $s"
        fi
    done
else
    for s in $runs_dir; do
        log "running script: $s"
        if [[ $dry_run == "0" ]]; then
            "$s"
        fi
    done
fi

