#!/usr/bin/env bash

# rust btw
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup update

git config --global user.email "mertins99@gmail.com"
git config --global user.name "Simon Mertins"

# lua btw
cargo install stylua
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.23.4.linux-amd64.tar.gz

# luarocks
pushd /tmp/luarocks-3.11.0
(
    wget --output-document /tmp/luarocks.tar.gz https://luarocks.org/releases/luarocks-3.11.0.tar.gz
    tar zxpf /tmp/luarocks.tar.gz -C /tmp
    cd
    ./configure && make && sudo make install
)
popd

luarocks install luacheck
